QT       += core gui network concurrent multimedia

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++14 console
LIBS += -lversion

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    accountmanagerwindow.cpp \
    intelligence/artificialintelligence.cpp \
    botmanager.cpp \
    intelligence/characteria.cpp \
    intelligence/nosmateia.cpp \
    intelligence/partneria.cpp \
    loginservice.cpp \
    main.cpp \
    mainwindow.cpp \
    modules/clickablelabel.cpp \
    modules/itemtablewidget.cpp \
    srcs/Database/databasemonster.cpp \
    srcs/GameObjects/Entity/mynosmate.cpp \
    srcs/GameObjects/Entity/mypartner.cpp \
    srcs/GameObjects/Instance/chatinstance.cpp \
    srcs/GameObjects/Properties/group.cpp \
    srcs/Packets/Client/World/packetblins.cpp \
    srcs/Packets/Client/World/packeteqinfo.cpp \
    srcs/Packets/Client/World/packetfins.cpp \
    srcs/Packets/Client/World/packetget.cpp \
    srcs/Packets/Client/World/packetgop.cpp \
    srcs/Packets/Client/World/packetguri.cpp \
    srcs/Packets/Client/World/packetpjoin.cpp \
    srcs/Packets/Client/World/packetpleave.cpp \
    srcs/Packets/Client/World/packetpsl.cpp \
    srcs/Packets/Client/World/packetptctl.cpp \
    srcs/Packets/Client/World/packetsay.cpp \
    srcs/Packets/Client/World/packetsaywhisper.cpp \
    srcs/Packets/Client/World/packetsl.cpp \
    srcs/Packets/Client/World/packetsuctl.cpp \
    srcs/Packets/Client/World/packetu_i.cpp \
    srcs/Packets/Client/World/packetu_pet.cpp \
    srcs/Packets/Client/World/packetu_ps.cpp \
    srcs/Packets/Server/World/packetc_mode.cpp \
    srcs/Packets/Server/World/packetdelay.cpp \
    srcs/Packets/Server/World/packetdlgi.cpp \
    srcs/Packets/Server/World/packetdlgi2.cpp \
    srcs/Packets/Server/World/packetdpski.cpp \
    srcs/Packets/Server/World/packeteff.cpp \
    srcs/Packets/Server/World/packetpdelay.cpp \
    srcs/Packets/Server/World/packetpetski.cpp \
    srcs/Packets/Server/World/packetpetsr.cpp \
    srcs/Packets/Server/World/packetpidx.cpp \
    srcs/Packets/Server/World/packetpinit.cpp \
    srcs/Packets/Server/World/packetpski.cpp \
    srcs/Packets/Server/World/packetpsr.cpp \
    srcs/Packets/Server/World/packetpst.cpp \
    srcs/Packets/Client/World/packetrest.cpp \
    srcs/Packets/Server/World/packetrestr.cpp \
    srcs/Packets/Server/World/packetrevive.cpp \
    srcs/Packets/Server/World/packetrp.cpp \
    srcs/Packets/Server/World/packetsayi2.cpp \
    srcs/Packets/Server/World/packetsayr.cpp \
    srcs/Packets/Server/World/packetsayt.cpp \
    srcs/Packets/Server/World/packetspk.cpp \
    srcs/Packets/Server/World/packettp.cpp \
    srcs/Packets/Server/World/packetzzim.cpp \
    widgets/accountconnectionwidget.cpp \
\
\
    srcs/Database/databaseitem.cpp \
    srcs/Database/databasemap.cpp \
    srcs/Database/databaseskill.cpp \
    srcs/GameObjects/Entity/drop.cpp \
    srcs/GameObjects/Entity/monster.cpp \
    srcs/GameObjects/Entity/mycharacter.cpp \
    srcs/GameObjects/Entity/nosmate.cpp \
    srcs/GameObjects/Entity/npc.cpp \
    srcs/GameObjects/Entity/player.cpp \
    srcs/GameObjects/Event/eventbase.cpp \
    srcs/GameObjects/Event/eventmanager.cpp \
    srcs/GameObjects/Event/instantcombatevent.cpp \
    srcs/GameObjects/Instance/timespaceinstance.cpp \
    srcs/GameObjects/Inventory/inventory.cpp \
    srcs/GameObjects/Inventory/item.cpp \
    srcs/GameObjects/Inventory/subinventory.cpp \
    srcs/GameObjects/Map/map.cpp \
    srcs/GameObjects/Map/portals.cpp \
    srcs/GameObjects/Map/ts.cpp \
    srcs/GameObjects/Properties/level.cpp \
    srcs/GameObjects/Properties/quest.cpp \
    srcs/GameObjects/Properties/reputation.cpp \
    srcs/GameObjects/Properties/shop.cpp \
    srcs/GameObjects/Properties/skill.cpp \
    srcs/GameObjects/Properties/statistics.cpp \
    srcs/Net/codegenerator.cpp \
    srcs/Net/credentials.cpp \
    srcs/Net/cryptography.cpp \
    srcs/Net/network.cpp \
    srcs/Net/networkrequester.cpp \
    srcs/Net/server.cpp \
    srcs/Packets/Client/World/packetc_close.cpp \
    srcs/Packets/Client/World/packetchar_del.cpp \
    srcs/Packets/Client/World/packetchar_new.cpp \
    srcs/Packets/Client/World/packetchar_new_job.cpp \
    srcs/Packets/Client/World/packetchar_ren.cpp \
    srcs/Packets/Client/World/packetf_stash_end.cpp \
    srcs/Packets/Client/World/packetgame_start.cpp \
    srcs/Packets/Client/World/packetglist.cpp \
    srcs/Packets/Client/World/packetlbs.cpp \
    srcs/Packets/Client/World/packetmvi.cpp \
    srcs/Packets/Client/World/packetnpinfo.cpp \
    srcs/Packets/Client/World/packetpreq.cpp \
    srcs/Packets/Client/World/packetpulse.cpp \
    srcs/Packets/Client/World/packetselect.cpp \
    srcs/Packets/Client/World/packettreq.cpp \
    srcs/Packets/Client/World/packetu_as.cpp \
    srcs/Packets/Client/World/packetu_s.cpp \
    srcs/Packets/Client/World/packetwalk.cpp \
    srcs/Packets/Client/World/packetwear.cpp \
    srcs/Packets/Client/World/packetwreq.cpp \
    srcs/Packets/Server/Login/packetfailc.cpp \
    srcs/Packets/Server/Login/packetnstest.cpp \
    srcs/Packets/Server/World/packetat.cpp \
    srcs/Packets/Server/World/packetc_info.cpp \
    srcs/Packets/Server/World/packetc_info_reset.cpp \
    srcs/Packets/Server/World/packetc_map.cpp \
    srcs/Packets/Server/World/packetcancel.cpp \
    srcs/Packets/Server/World/packetclist.cpp \
    srcs/Packets/Server/World/packetclist_end.cpp \
    srcs/Packets/Server/World/packetclist_start.cpp \
    srcs/Packets/Server/World/packetcond.cpp \
    srcs/Packets/Server/World/packetdie.cpp \
    srcs/Packets/Server/World/packetdrop.cpp \
    srcs/Packets/Server/World/packetesf.cpp \
    srcs/Packets/Server/World/packetfd.cpp \
    srcs/Packets/Server/World/packetgetr.cpp \
    srcs/Packets/Server/World/packetgold.cpp \
    srcs/Packets/Server/World/packetgp.cpp \
    srcs/Packets/Server/World/packetin.cpp \
    srcs/Packets/Server/World/packetinfo.cpp \
    srcs/Packets/Server/World/packetinv.cpp \
    srcs/Packets/Server/World/packetivn.cpp \
    srcs/Packets/Server/World/packetlev.cpp \
    srcs/Packets/Server/World/packetms_c.cpp \
    srcs/Packets/Server/World/packetmslot.cpp \
    srcs/Packets/Server/World/packetmv.cpp \
    srcs/Packets/Server/World/packetok.cpp \
    srcs/Packets/Server/World/packetout.cpp \
    srcs/Packets/Server/World/packetqnamli.cpp \
    srcs/Packets/Server/World/packetrsfi.cpp \
    srcs/Packets/Server/World/packetsc_p_stc.cpp \
    srcs/Packets/Server/World/packetshop.cpp \
    srcs/Packets/Server/World/packetski.cpp \
    srcs/Packets/Server/World/packetsr.cpp \
    srcs/Packets/Server/World/packetstat.cpp \
    srcs/Packets/Server/World/packetsu.cpp \
    srcs/Packets/Server/World/packetsuccess.cpp \
    srcs/Packets/Server/World/packettit.cpp \
    srcs/Packets/Server/World/packetwp.cpp \
    srcs/Utils/Pathfinding/pathfinding.cpp \
    srcs/bot.cpp \
    widgets/behaviourwidget.cpp \
    widgets/botwidget.cpp \
    widgets/channelwidget.cpp \
    widgets/characterwidget.cpp \
    widgets/dropwidget.cpp \
    widgets/formbase.cpp \
    widgets/headerwidget.cpp \
    widgets/inventorywidget.cpp \
    widgets/itemusewidget.cpp \
    widgets/mapwidget.cpp \
    widgets/monsterwidget.cpp \
    widgets/pathingwidget.cpp \
    widgets/securitywidget.cpp \
    widgets/skillswidget.cpp \
    widgets/userswidget.cpp


HEADERS += \
    accountmanagerwindow.h \
    intelligence/artificialintelligence.h \
    botmanager.h \
    intelligence/characteria.h \
    intelligence/nosmateia.h \
    intelligence/partneria.h \
    loginservice.h \
    mainwindow.h \
    modules/clickablelabel.h \
    modules/itemtablewidget.h \
    srcs/Database/databasemonster.h \
    srcs/Enum/blockingoption.h \
    srcs/Enum/chatenum.h \
    srcs/Enum/partyenum.h \
    srcs/GameObjects/Entity/mynosmate.h \
    srcs/GameObjects/Entity/mypartner.h \
    srcs/GameObjects/Instance/chatinstance.h \
    srcs/GameObjects/Properties/group.h \
    srcs/Packets/Client/World/packetblins.h \
    srcs/Packets/Client/World/packeteqinfo.h \
    srcs/Packets/Client/World/packetfins.h \
    srcs/Packets/Client/World/packetget.h \
    srcs/Packets/Client/World/packetgop.h \
    srcs/Packets/Client/World/packetguri.h \
    srcs/Packets/Client/World/packetpjoin.h \
    srcs/Packets/Client/World/packetpleave.h \
    srcs/Packets/Client/World/packetpsl.h \
    srcs/Packets/Client/World/packetptctl.h \
    srcs/Packets/Client/World/packetsay.h \
    srcs/Packets/Client/World/packetsaywhisper.h \
    srcs/Packets/Client/World/packetsl.h \
    srcs/Packets/Client/World/packetsuctl.h \
    srcs/Packets/Client/World/packetu_i.h \
    srcs/Packets/Client/World/packetu_pet.h \
    srcs/Packets/Client/World/packetu_ps.h \
    srcs/Packets/Server/World/packetc_mode.h \
    srcs/Packets/Server/World/packetdelay.h \
    srcs/Packets/Server/World/packetdlgi.h \
    srcs/Packets/Server/World/packetdlgi2.h \
    srcs/Packets/Server/World/packetdpski.h \
    srcs/Packets/Server/World/packeteff.h \
    srcs/Packets/Server/World/packetpdelay.h \
    srcs/Packets/Server/World/packetpetski.h \
    srcs/Packets/Server/World/packetpetsr.h \
    srcs/Packets/Server/World/packetpidx.h \
    srcs/Packets/Server/World/packetpinit.h \
    srcs/Packets/Server/World/packetpski.h \
    srcs/Packets/Server/World/packetpsr.h \
    srcs/Packets/Server/World/packetpst.h \
    srcs/Packets/Client/World/packetrest.h \
    srcs/Packets/Server/World/packetrestr.h \
    srcs/Packets/Server/World/packetrevive.h \
    srcs/Packets/Server/World/packetrp.h \
    srcs/Packets/Server/World/packetsayi2.h \
    srcs/Packets/Server/World/packetsayr.h \
    srcs/Packets/Server/World/packetsayt.h \
    srcs/Packets/Server/World/packetspk.h \
    srcs/Packets/Server/World/packettp.h \
    srcs/Packets/Server/World/packetzzim.h \
    widgets/accountconnectionwidget.h \
\
\
    srcs/Database/databaseitem.h \
    srcs/Database/databasemap.h \
    srcs/Database/databaseskill.h \
    srcs/Enum/attackenum.h \
    srcs/Enum/cancelenum.h \
    srcs/Enum/characterenum.h \
    srcs/Enum/entityenum.h \
    srcs/Enum/eventenum.h \
    srcs/Enum/factionenum.h \
    srcs/Enum/failcenum.h \
    srcs/Enum/fairyenum.h \
    srcs/Enum/inventoryenum.h \
    srcs/Enum/mapenum.h \
    srcs/Enum/portalenum.h \
    srcs/Enum/reputationenum.h \
    srcs/Enum/skillenum.h \
    srcs/Enum/timespaceenum.h \
    srcs/Enum/wingsenum.h \
    srcs/GameObjects/Entity/baseentity.h \
    srcs/GameObjects/Entity/drop.h \
    srcs/GameObjects/Entity/monster.h \
    srcs/GameObjects/Entity/mycharacter.h \
    srcs/GameObjects/Entity/nosmate.h \
    srcs/GameObjects/Entity/npc.h \
    srcs/GameObjects/Entity/player.h \
    srcs/GameObjects/Event/eventbase.h \
    srcs/GameObjects/Event/eventmanager.h \
    srcs/GameObjects/Event/instantcombatevent.h \
    srcs/GameObjects/Instance/timespaceinstance.h \
    srcs/GameObjects/Inventory/inventory.h \
    srcs/GameObjects/Inventory/item.h \
    srcs/GameObjects/Inventory/subinventory.h \
    srcs/GameObjects/Map/map.h \
    srcs/GameObjects/Map/portals.h \
    srcs/GameObjects/Map/ts.h \
    srcs/GameObjects/Properties/level.h \
    srcs/GameObjects/Properties/quest.h \
    srcs/GameObjects/Properties/reputation.h \
    srcs/GameObjects/Properties/shop.h \
    srcs/GameObjects/Properties/skill.h \
    srcs/GameObjects/Properties/statistics.h \
    srcs/Net/codegenerator.h \
    srcs/Net/credentials.h \
    srcs/Net/cryptography.h \
    srcs/Net/network.h \
    srcs/Net/networkrequester.h \
    srcs/Net/server.h \
    srcs/Packets/Client/World/packetc_close.h \
    srcs/Packets/Client/World/packetchar_del.h \
    srcs/Packets/Client/World/packetchar_new.h \
    srcs/Packets/Client/World/packetchar_new_job.h \
    srcs/Packets/Client/World/packetchar_ren.h \
    srcs/Packets/Client/World/packetf_stash_end.h \
    srcs/Packets/Client/World/packetgame_start.h \
    srcs/Packets/Client/World/packetglist.h \
    srcs/Packets/Client/World/packetlbs.h \
    srcs/Packets/Client/World/packetmvi.h \
    srcs/Packets/Client/World/packetnpinfo.h \
    srcs/Packets/Client/World/packetpreq.h \
    srcs/Packets/Client/World/packetpulse.h \
    srcs/Packets/Client/World/packetselect.h \
    srcs/Packets/Client/World/packettreq.h \
    srcs/Packets/Client/World/packetu_as.h \
    srcs/Packets/Client/World/packetu_s.h \
    srcs/Packets/Client/World/packetwalk.h \
    srcs/Packets/Client/World/packetwear.h \
    srcs/Packets/Client/World/packetwreq.h \
    srcs/Packets/Server/Login/packetfailc.h \
    srcs/Packets/Server/Login/packetnstest.h \
    srcs/Packets/Server/World/packetat.h \
    srcs/Packets/Server/World/packetc_info.h \
    srcs/Packets/Server/World/packetc_info_reset.h \
    srcs/Packets/Server/World/packetc_map.h \
    srcs/Packets/Server/World/packetcancel.h \
    srcs/Packets/Server/World/packetclist.h \
    srcs/Packets/Server/World/packetclist_end.h \
    srcs/Packets/Server/World/packetclist_start.h \
    srcs/Packets/Server/World/packetcond.h \
    srcs/Packets/Server/World/packetdie.h \
    srcs/Packets/Server/World/packetdrop.h \
    srcs/Packets/Server/World/packetesf.h \
    srcs/Packets/Server/World/packetfd.h \
    srcs/Packets/Server/World/packetgetr.h \
    srcs/Packets/Server/World/packetgold.h \
    srcs/Packets/Server/World/packetgp.h \
    srcs/Packets/Server/World/packetin.h \
    srcs/Packets/Server/World/packetinfo.h \
    srcs/Packets/Server/World/packetinv.h \
    srcs/Packets/Server/World/packetivn.h \
    srcs/Packets/Server/World/packetlev.h \
    srcs/Packets/Server/World/packetms_c.h \
    srcs/Packets/Server/World/packetmslot.h \
    srcs/Packets/Server/World/packetmv.h \
    srcs/Packets/Server/World/packetok.h \
    srcs/Packets/Server/World/packetout.h \
    srcs/Packets/Server/World/packetqnamli.h \
    srcs/Packets/Server/World/packetrsfi.h \
    srcs/Packets/Server/World/packetsc_p_stc.h \
    srcs/Packets/Server/World/packetshop.h \
    srcs/Packets/Server/World/packetski.h \
    srcs/Packets/Server/World/packetsr.h \
    srcs/Packets/Server/World/packetstat.h \
    srcs/Packets/Server/World/packetsu.h \
    srcs/Packets/Server/World/packetsuccess.h \
    srcs/Packets/Server/World/packettit.h \
    srcs/Packets/Server/World/packetwp.h \
    srcs/Packets/basepacket.h \
    srcs/Packets/packetidentification.h \
    srcs/Utils/Pathfinding/pathfinding.h \
    srcs/bot.h \
    widgets/behaviourwidget.h \
    widgets/botwidget.h \
    widgets/channelwidget.h \
    widgets/characterwidget.h \
    widgets/dropwidget.h \
    widgets/formbase.h \
    widgets/headerwidget.h \
    widgets/inventorywidget.h \
    widgets/itemusewidget.h \
    widgets/mapwidget.h \
    widgets/monsterwidget.h \
    widgets/pathingwidget.h \
    widgets/securitywidget.h \
    widgets/skillswidget.h \
    widgets/userswidget.h

FORMS += \
    accountmanagerwindow.ui \
    loginservice.ui \
    mainwindow.ui \
    widgets/accountconnectionwidget.ui \
    widgets/behaviourwidget.ui \
    widgets/botwidget.ui \
    widgets/channelwidget.ui \
    widgets/characterwidget.ui \
    widgets/dropwidget.ui \
    widgets/headerwidget.ui \
    widgets/inventorywidget.ui \
    widgets/itemusewidget.ui \
    widgets/mapwidget.ui \
    widgets/monsterwidget.ui \
    widgets/pathingwidget.ui \
    widgets/securitywidget.ui \
    widgets/skillswidget.ui \
    widgets/userswidget.ui

RESOURCES = guires.qrc

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
